namespace: master
resources:
  - ../../base

images:
  - name: diegoapolancol/circleguard-auth-service
    newTag: master
  - name: diegoapolancol/circleguard-identity-service
    newTag: master
  - name: diegoapolancol/circleguard-promotion-service
    newTag: master
  - name: diegoapolancol/circleguard-gateway-service
    newTag: master
  - name: diegoapolancol/circleguard-dashboard-service
    newTag: master
  - name: diegoapolancol/circleguard-file-service
    newTag: master