qr.secret=${QR_SECRET:change-me}
jwt.secret=${QR_SECRET:change-me}
jwt.expiration=3600000
qr.expiration=3600000

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
