namespace: prod
resources:
  - ../../base

images:
  - name: TU_USUARIO_DOCKERHUB/circleguard-identity-service
    newTag: prod
  - name: TU_USUARIO_DOCKERHUB/circleguard-auth-service
    newTag: prod
  - name: TU_USUARIO_DOCKERHUB/circleguard-promotion-service
    newTag: prod
  - name: TU_USUARIO_DOCKERHUB/circleguard-gateway-service
    newTag: prod
  - name: TU_USUARIO_DOCKERHUB/circleguard-form-service
    newTag: prod
  - name: TU_USUARIO_DOCKERHUB/circleguard-notification-service
    newTag: prod
