namespace: stage
resources:
  - ../../base

images:
  - name: diegoapolancol/circleguard-identity-service
    newTag: stage
  - name: diegoapolancol/circleguard-auth-service
    newTag: stage
  - name: diegoapolancol/circleguard-promotion-service
    newTag: stage
  - name: diegoapolancol/circleguard-gateway-service
    newTag: stage
  - name: diegoapolancol/circleguard-form-service
    newTag: stage
  - name: diegoapolancol/circleguard-notification-service
    newTag: stage
