apiVersion: v1
kind: Secret
metadata:
  name: app-config
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/circleguard"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_FLYWAY_VALIDATE_ON_MIGRATE: "false"
  VAULT_SECRET: "test-secret-32-chars-long-123456"
  VAULT_SALT: "deadbeef"
  VAULT_HASH_SALT: "12345678"
  SPRING_NEO4J_URI: "bolt://neo4j:7687"
  SPRING_NEO4J_AUTHENTICATION_USERNAME: "neo4j"
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: "password"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  IDENTITY_SERVICE_URL: "http://circleguard-identity-service"
  LDAP_URL: "ldap://openldap:389"
  LDAP_BASE: "dc=circleguard,dc=edu"
  LDAP_USER_DN: "cn=admin,dc=circleguard,dc=edu"
  LDAP_PASSWORD: "admin"
  MANAGEMENT_HEALTH_LDAP_ENABLED: "false"
