resources:
  - services-deployments.yaml
  - infra-deployments.yaml
  - app-config-secret.yaml
  - qr-secret.yaml

configMapGenerator:
  - name: circleguard-config
    literals:
      - example=placeholder

images:
  - name: diegoapolancol/circleguard-identity-service
    newName: diegoapolancol/circleguard-identity-service
    newTag: dev
  - name: diegoapolancol/circleguard-auth-service
    newName: diegoapolancol/circleguard-auth-service
    newTag: dev
  - name: diegoapolancol/circleguard-promotion-service
    newName: diegoapolancol/circleguard-promotion-service
    newTag: dev
  - name: diegoapolancol/circleguard-gateway-service
    newName: diegoapolancol/circleguard-gateway-service
    newTag: dev
  - name: diegoapolancol/circleguard-form-service
    newName: diegoapolancol/circleguard-form-service
    newTag: dev
  - name: diegoapolancol/circleguard-notification-service
    newName: diegoapolancol/circleguard-notification-service
    newTag: dev
