apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-identity-service
  template:
    metadata:
      labels:
        app: circleguard-identity-service
    spec:
      containers:
        - name: identity
          image: TU_USUARIO_DOCKERHUB/circleguard-identity-service:dev
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-identity-service
spec:
  selector:
    app: circleguard-identity-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-auth-service
  template:
    metadata:
      labels:
        app: circleguard-auth-service
    spec:
      containers:
        - name: auth
          image: TU_USUARIO_DOCKERHUB/circleguard-auth-service:dev
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-auth-service
spec:
  selector:
    app: circleguard-auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-promotion-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-promotion-service
  template:
    metadata:
      labels:
        app: circleguard-promotion-service
    spec:
      containers:
        - name: promotion
          image: TU_USUARIO_DOCKERHUB/circleguard-promotion-service:dev
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-promotion-service
spec:
  selector:
    app: circleguard-promotion-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-gateway-service
  template:
    metadata:
      labels:
        app: circleguard-gateway-service
    spec:
      containers:
        - name: gateway
          image: TU_USUARIO_DOCKERHUB/circleguard-gateway-service:dev
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-gateway-service
spec:
  selector:
    app: circleguard-gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-form-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-form-service
  template:
    metadata:
      labels:
        app: circleguard-form-service
    spec:
      containers:
        - name: form
          image: TU_USUARIO_DOCKERHUB/circleguard-form-service:dev
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-form-service
spec:
  selector:
    app: circleguard-form-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: circleguard-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: circleguard-notification-service
  template:
    metadata:
      labels:
        app: circleguard-notification-service
    spec:
      containers:
        - name: notification
          image: TU_USUARIO_DOCKERHUB/circleguard-notification-service:dev
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: circleguard-notification-service
spec:
  selector:
    app: circleguard-notification-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
